# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'B:\ui bus\admin_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator


class Ui_Adm(object):
    def setupUi(self, Adm):
        Adm.setObjectName("Adm")
        Adm.resize(1518, 704)
        Adm.setStyleSheet("QWidget{\n"
"background-color: #73D5FF;\n"
"color: #fff;\n"
"border: 3px solid #000;\n"
"}\n"
"QLineEdit{\n"
"background-color: #73D5FF;\n"
"color: #000;\n"
"font-size: 13pt;\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: #73D5FF;\n"
"color: #fff;\n"
"font-size: 12pt;\n"
"font-weight: 800;\n"
"}\n"
"\n"
"QPushButton#exit{\n"
"color: #808080;\n"
"font-size: 14pt;\n"
"}\n"
"\n"
"\n"
"QPushButton#exit:hover{\n"
"color: #ff0000;\n"
"font-size: 18pt;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: #ff0000;\n"
"font-size: 14pt;\n"
"}\n"
"\n"
"QTableWidget{\n"
"color: #000;\n"
"}")
        self.tableWidget = QtWidgets.QTableWidget(Adm)
        self.tableWidget.setGeometry(QtCore.QRect(9, 59, 1501, 611))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(1301, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(10000000, 16777215))
        self.tableWidget.setBaseSize(QtCore.QSize(0, 0))
        self.tableWidget.setToolTipDuration(0)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setStyleSheet("color: #000;")
        self.tableWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setAutoScrollMargin(16)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setDragDropOverwriteMode(True)
        self.tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableWidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        item.setBackground(QtGui.QColor(115, 213, 255))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 0, 0))
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(215)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(18)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(18)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.pushButton_row_plu = QtWidgets.QPushButton(Adm)
        self.pushButton_row_plu.setGeometry(QtCore.QRect(9, 674, 741, 25))
        self.pushButton_row_plu.setMaximumSize(QtCore.QSize(16777, 25))
        self.pushButton_row_plu.setObjectName("pushButton_row_plu")
        self.pushButton_row_min = QtWidgets.QPushButton(Adm)
        self.pushButton_row_min.setGeometry(QtCore.QRect(770, 674, 741, 25))
        self.pushButton_row_min.setMaximumSize(QtCore.QSize(16777, 25))
        self.pushButton_row_min.setObjectName("pushButton_row_min")
        self.lineEdit_distance = QtWidgets.QLineEdit(Adm)
        self.lineEdit_distance.setGeometry(QtCore.QRect(240, 10, 201, 41))
        self.lineEdit_distance.setStyleSheet("border: 3px double #fff;\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.lineEdit_distance.setReadOnly(False)
        self.lineEdit_distance.setObjectName("lineEdit_distance")
        self.lineEdit_name = QtWidgets.QLineEdit(Adm)
        self.lineEdit_name.setGeometry(QtCore.QRect(50, 10, 181, 41))
        self.lineEdit_name.setAutoFillBackground(False)
        self.lineEdit_name.setStyleSheet("border: 3px double #fff;\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.lineEdit_name.setReadOnly(False)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.lineEdit_price = QtWidgets.QLineEdit(Adm)
        self.lineEdit_price.setGeometry(QtCore.QRect(450, 10, 211, 41))
        self.lineEdit_price.setStyleSheet("border: 3px double #fff;\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.lineEdit_price.setReadOnly(False)
        self.lineEdit_price.setObjectName("lineEdit_price")
        self.lineEdit_dw = QtWidgets.QLineEdit(Adm)
        self.lineEdit_dw.setGeometry(QtCore.QRect(670, 10, 201, 41))
        self.lineEdit_dw.setStyleSheet("border: 3px double #fff;\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.lineEdit_dw.setReadOnly(False)
        self.lineEdit_dw.setObjectName("lineEdit_dw")
        self.lineEdit_sp = QtWidgets.QLineEdit(Adm)
        self.lineEdit_sp.setGeometry(QtCore.QRect(880, 10, 201, 41))
        self.lineEdit_sp.setStyleSheet("border: 3px double #fff;\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.lineEdit_sp.setReadOnly(False)
        self.lineEdit_sp.setObjectName("lineEdit_sp")
        self.lineEdit_fp = QtWidgets.QLineEdit(Adm)
        self.lineEdit_fp.setGeometry(QtCore.QRect(1090, 10, 211, 41))
        self.lineEdit_fp.setStyleSheet("border: 3px double #fff;\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.lineEdit_fp.setReadOnly(False)
        self.lineEdit_fp.setObjectName("lineEdit_fp")
        self.exit = QtWidgets.QPushButton(Adm)
        self.exit.setGeometry(QtCore.QRect(10, 10, 31, 41))
        self.exit.setStyleSheet("")
        self.exit.setObjectName("exit")
        self.lineEdit_qt = QtWidgets.QLineEdit(Adm)
        self.lineEdit_qt.setGeometry(QtCore.QRect(1310, 10, 201, 41))
        self.lineEdit_qt.setStyleSheet("border: 3px double #fff;\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.lineEdit_qt.setReadOnly(False)
        self.lineEdit_qt.setObjectName("lineEdit_qt")

        self.retranslateUi(Adm)
        QtCore.QMetaObject.connectSlotsByName(Adm)

    def retranslateUi(self, Adm):
        _translate = QtCore.QCoreApplication.translate
        Adm.setWindowTitle(_translate("Adm", "Админ панель"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Adm", "Имя"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Adm", "Расстояние"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Adm", "Цена"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Adm", "Дни в недели"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Adm", "Начальная точка"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Adm", "Конечная точка"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Adm", "Количество"))
        self.pushButton_row_plu.setText(_translate("Adm", "+"))
        self.pushButton_row_min.setText(_translate("Adm", "—"))
        self.lineEdit_distance.setPlaceholderText(_translate("Adm", "Расстояние"))
        self.lineEdit_distance.setValidator(QRegExpValidator(QRegExp("[0-9]*")))
        self.lineEdit_name.setPlaceholderText(_translate("Adm", "Имя"))
        self.lineEdit_price.setPlaceholderText(_translate("Adm", "Цена"))
        self.lineEdit_price.setValidator(QRegExpValidator(QRegExp("[0-9]*")))
        self.lineEdit_dw.setPlaceholderText(_translate("Adm", "Дни в недели"))
        self.lineEdit_sp.setPlaceholderText(_translate("Adm", "Начальная точка"))
        self.lineEdit_fp.setPlaceholderText(_translate("Adm", "Конечная точка"))
        self.exit.setText(_translate("Adm", "X"))
        self.lineEdit_qt.setPlaceholderText(_translate("Adm", "Количество"))
        self.lineEdit_qt.setValidator(QRegExpValidator(QRegExp("[0-9]*")))
