# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'B:\ui bus\enter.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Enter(object):
    def setupUi(self, Enter):
        Enter.setObjectName("Enter")
        Enter.resize(405, 296)
        Enter.setStyleSheet("QWidget{\n"
"background: #fff;\n"
"}\n"
"\n"
"QPushButton#enter_button_registration{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: #73d5ff;\n"
"border-color: #000;\n"
"color: fff;\n"
"background-color: #73D5FF;\n"
"color: #000;\n"
"font-size: 13px;\n"
"}\n"
"\n"
"QPushButton#enter_button_registration:hover{\n"
"font-weight: 600;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: #fff;\n"
"}\n"
"\n"
"QPushButton#enter_button_enter{\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: #73d5ff;\n"
"border-color: #000;\n"
"color: fff;\n"
"background-color: #73D5FF;\n"
"color: #000;\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#enter_button_enter:hover{\n"
"font-weight: 600;\n"
"font: 75 17pt \"MS Shell Dlg 2\";\n"
"color: #fff;\n"
"}\n"
"")
        self.enter_button_registration = QtWidgets.QPushButton(Enter)
        self.enter_button_registration.setGeometry(QtCore.QRect(270, 10, 121, 41))
        self.enter_button_registration.setStyleSheet("")
        self.enter_button_registration.setObjectName("enter_button_registration")
        self.enter_text_login = QtWidgets.QTextEdit(Enter)
        self.enter_text_login.setGeometry(QtCore.QRect(140, 140, 231, 31))
        self.enter_text_login.setStyleSheet("")
        self.enter_text_login.setObjectName("enter_text_login")
        self.textEdit_3 = QtWidgets.QTextEdit(Enter)
        self.textEdit_3.setGeometry(QtCore.QRect(50, 140, 71, 31))
        self.textEdit_3.setStyleSheet("border-radius: 0px;\n"
"")
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(Enter)
        self.textEdit_4.setGeometry(QtCore.QRect(50, 190, 71, 31))
        self.textEdit_4.setStyleSheet("border-radius: 0px;\n"
"")
        self.textEdit_4.setObjectName("textEdit_4")
        self.enter_button_enter = QtWidgets.QPushButton(Enter)
        self.enter_button_enter.setGeometry(QtCore.QRect(240, 240, 131, 41))
        self.enter_button_enter.setStyleSheet("")
        self.enter_button_enter.setObjectName("enter_button_enter")
        self.enter_text_password = QtWidgets.QLineEdit(Enter)
        self.enter_text_password.setGeometry(QtCore.QRect(140, 190, 231, 31))
        self.enter_text_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.enter_text_password.setObjectName("enter_text_password")

        self.retranslateUi(Enter)
        QtCore.QMetaObject.connectSlotsByName(Enter)

    def retranslateUi(self, Enter):
        _translate = QtCore.QCoreApplication.translate
        Enter.setWindowTitle(_translate("Enter", "Авторизация"))
        self.enter_button_registration.setText(_translate("Enter", "Регистрация →"))
        self.enter_text_login.setHtml(_translate("Enter", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_3.setHtml(_translate("Enter", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Логин</span></p></body></html>"))
        self.textEdit_4.setHtml(_translate("Enter", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Пароль</span></p></body></html>"))
        self.enter_button_enter.setText(_translate("Enter", "Войти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Enter = QtWidgets.QDialog()
    ui = Ui_Enter()
    ui.setupUi(Enter)
    Enter.show()
    sys.exit(app.exec_())
