# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'B:\ui bus\registration_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Registration(object):
    def setupUi(self, registration_form):
        registration_form.setObjectName("registration_form")
        registration_form.resize(400, 300)
        registration_form.setStyleSheet("QWidget{\n"
"background: #fff;\n"
"}\n"
"\n"
"QPushButton#registration_button_enter{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: #73D5FF;\n"
"border-color: #fff;\n"
"color: fff;\n"
"color: #000;\n"
"font-size: 13px;\n"
"}\n"
"\n"
"QPushButton#registration_button_enter:hover{\n"
"font-weight: 600;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: #fff;\n"
"}\n"
"\n"
"QPushButton#registration_button_registration{\n"
"font: 75 11pt \"MS Shell Dlg 2\";\n"
"background-color: #73D5FF;\n"
"border-color: #fff;\n"
"color: fff;\n"
"color: #000;\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton#registration_button_registration:hover{\n"
"font-weight: 600;\n"
"font: 75 15pt \"MS Shell Dlg 2\";\n"
"color: #fff;\n"
"}\n"
"")
        self.registration_button_enter = QtWidgets.QPushButton(registration_form)
        self.registration_button_enter.setGeometry(QtCore.QRect(10, 10, 101, 31))
        self.registration_button_enter.setStyleSheet("")
        self.registration_button_enter.setObjectName("registration_button_enter")
        self.textEdit_3 = QtWidgets.QTextEdit(registration_form)
        self.textEdit_3.setGeometry(QtCore.QRect(10, 90, 71, 31))
        self.textEdit_3.setStyleSheet("border-radius: 0px;\n"
"")
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(registration_form)
        self.textEdit_4.setGeometry(QtCore.QRect(10, 140, 71, 31))
        self.textEdit_4.setStyleSheet("border-radius: 0px;\n"
"")
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(registration_form)
        self.textEdit_5.setGeometry(QtCore.QRect(10, 190, 151, 31))
        self.textEdit_5.setStyleSheet("border-radius: 0px;\n"
"")
        self.textEdit_5.setObjectName("textEdit_5")
        self.registration_text_login = QtWidgets.QTextEdit(registration_form)
        self.registration_text_login.setGeometry(QtCore.QRect(160, 80, 231, 31))
        self.registration_text_login.setStyleSheet("")
        self.registration_text_login.setObjectName("registration_text_login")
        self.registration_text_password_repeat = QtWidgets.QLineEdit(registration_form)
        self.registration_text_password_repeat.setGeometry(QtCore.QRect(160, 180, 231, 31))
        self.registration_text_password_repeat.setEchoMode(QtWidgets.QLineEdit.Password)
        self.registration_text_password_repeat.setObjectName("registration_text_password_repeat")
        self.registration_text_password = QtWidgets.QLineEdit(registration_form)
        self.registration_text_password.setGeometry(QtCore.QRect(160, 130, 231, 31))
        self.registration_text_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.registration_text_password.setObjectName("registration_text_password")
        self.registration_button_registration = QtWidgets.QPushButton(registration_form)
        self.registration_button_registration.setGeometry(QtCore.QRect(200, 240, 191, 41))
        self.registration_button_registration.setStyleSheet("")
        self.registration_button_registration.setObjectName("registration_button_registration")

        self.retranslateUi(registration_form)
        QtCore.QMetaObject.connectSlotsByName(registration_form)

    def retranslateUi(self, registration_form):
        _translate = QtCore.QCoreApplication.translate
        registration_form.setWindowTitle(_translate("registration_form", "Регистрация"))
        self.registration_button_enter.setText(_translate("registration_form", "← Вход"))
        self.textEdit_3.setHtml(_translate("registration_form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Логин</span></p></body></html>"))
        self.textEdit_4.setHtml(_translate("registration_form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Пароль</span></p></body></html>"))
        self.textEdit_5.setHtml(_translate("registration_form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">Подтвердите пароль</span></p></body></html>"))
        self.registration_text_login.setHtml(_translate("registration_form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.registration_button_registration.setText(_translate("registration_form", "Зарегестрироваться"))
