# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'B:\ДЗ\Bus schedule\user_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_User(object):
    def setupUi(self, User):
        User.setObjectName("User")
        User.resize(1519, 715)
        User.setStyleSheet("QWidget{\n"
"background-color: #73D5FF;\n"
"color: #fff;\n"
"border: 3px solid #000;\n"
"}\n"
"QLineEdit{\n"
"background-color: #73D5FF;\n"
"color: #000;\n"
"border: 3px double #fff;\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton#exit{\n"
"color: #808080;\n"
"font-size: 14pt;\n"
"}\n"
"\n"
"\n"
"QPushButton#exit:hover{\n"
"font-weight: 800;\n"
"color: #ff0000;\n"
"font-size: 18pt;\n"
"}\n"
"\n"
"\n"
"QTableWidget{\n"
"color: #000;\n"
"}")
        self.tableWidget = QtWidgets.QTableWidget(User)
        self.tableWidget.setGeometry(QtCore.QRect(9, 59, 1501, 651))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(1301, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(10000000, 16777215))
        self.tableWidget.setBaseSize(QtCore.QSize(0, 0))
        self.tableWidget.setToolTipDuration(0)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setStyleSheet("color: #000;")
        self.tableWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setAutoScrollMargin(16)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setDragDropOverwriteMode(True)
        self.tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableWidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(215)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(18)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(18)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.lineEdit_count = QtWidgets.QLineEdit(User)
        self.lineEdit_count.setGeometry(QtCore.QRect(1310, 10, 201, 41))
        self.lineEdit_count.setStyleSheet("")
        self.lineEdit_count.setDragEnabled(False)
        self.lineEdit_count.setReadOnly(True)
        self.lineEdit_count.setObjectName("lineEdit_count")
        self.exit = QtWidgets.QPushButton(User)
        self.exit.setGeometry(QtCore.QRect(10, 10, 31, 41))
        self.exit.setStyleSheet("")
        self.exit.setObjectName("exit")

        self.retranslateUi(User)
        QtCore.QMetaObject.connectSlotsByName(User)

    def retranslateUi(self, User):
        _translate = QtCore.QCoreApplication.translate
        User.setWindowTitle(_translate("User", "Покупка Авиабилетов"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("User", "Имя"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("User", "Расстояние"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("User", "Цена"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("User", "Дни в недели"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("User", "Начальная точка"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("User", "Конечная точка"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("User", "Билеты"))
        self.exit.setText(_translate("User", "X"))
