# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'B:\ДЗ\Bus schedule\user_by_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_User_by(object):
    def setupUi(self, User_by):
        User_by.setObjectName("User_by")
        User_by.resize(400, 300)
        User_by.setStyleSheet("background-color: #fff;\n"
"")
        self.textEdit_4 = QtWidgets.QTextEdit(User_by)
        self.textEdit_4.setGeometry(QtCore.QRect(100, 10, 211, 31))
        self.textEdit_4.setStyleSheet("border-radius: 0px;\n"
"")
        self.textEdit_4.setReadOnly(True)
        self.textEdit_4.setObjectName("textEdit_4")
        self.user_flight_text_number_tickets = QtWidgets.QTextEdit(User_by)
        self.user_flight_text_number_tickets.setGeometry(QtCore.QRect(20, 240, 181, 31))
        self.user_flight_text_number_tickets.setObjectName("user_flight_text_number_tickets")
        self.user_flight_button_buy_ticket = QtWidgets.QPushButton(User_by)
        self.user_flight_button_buy_ticket.setGeometry(QtCore.QRect(240, 240, 131, 31))
        self.user_flight_button_buy_ticket.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: #73d5ff;\n"
"border-color: #000;\n"
"color: fff;\n"
"\n"
"")
        self.user_flight_button_buy_ticket.setObjectName("user_flight_button_buy_ticket")
        self.user_flight_button_back = QtWidgets.QPushButton(User_by)
        self.user_flight_button_back.setGeometry(QtCore.QRect(10, 10, 81, 31))
        self.user_flight_button_back.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: #73d5ff;\n"
"border-color: #000;\n"
"color: fff;\n"
"\n"
"")
        self.user_flight_button_back.setObjectName("user_flight_button_back")
        self.lineEdit_start = QtWidgets.QLineEdit(User_by)
        self.lineEdit_start.setGeometry(QtCore.QRect(20, 120, 151, 41))
        self.lineEdit_start.setStyleSheet("border: 0px;")
        self.lineEdit_start.setReadOnly(True)
        self.lineEdit_start.setObjectName("lineEdit_start")
        self.lineEdit_finish = QtWidgets.QLineEdit(User_by)
        self.lineEdit_finish.setGeometry(QtCore.QRect(230, 120, 151, 41))
        self.lineEdit_finish.setStyleSheet("border: 0px;")
        self.lineEdit_finish.setReadOnly(True)
        self.lineEdit_finish.setObjectName("lineEdit_finish")


        self.retranslateUi(User_by)
        QtCore.QMetaObject.connectSlotsByName(User_by)

    def retranslateUi(self, User_by):
        _translate = QtCore.QCoreApplication.translate
        User_by.setWindowTitle(_translate("User_by", "Покупка билета"))
        self.textEdit_4.setHtml(_translate("User_by", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Ифнормация о рейсе</span></p></body></html>"))
        self.user_flight_text_number_tickets.setHtml(_translate("User_by", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.user_flight_text_number_tickets.setPlaceholderText(_translate("User_by", "Введите количество билетов"))
        self.user_flight_button_buy_ticket.setText(_translate("User_by", "Купить"))
        self.user_flight_button_back.setText(_translate("User_by", "← Назад"))
